routes/web.php
<?php


// Route::get('/test', function() {
// 	return Devmus\Model\User\Profile::find(1)->user;
// });


Auth::routes();



/*Front End*/
Route::namespace('User')->group(function(){

	Route::get('/', 'HomeController@index')->name('home');


	// Profile
	Route::get('/dashboard', 'ProfileController@index')->name('user.dashboard');
	Route::post('/dashboard', 'ProfileController@update');
	Route::delete('/dashboard', 'ProfileController@destroy');


	// Blog

	Route::get('/', 'BlogController@list')->name('blog');
	
	Route::get('/{slug}', 'BlogController@post')->name('post');

	Route::get('/category/{category}', 'BlogController@category')->name('category');

	Route::get('/tag/{tag}', 'BlogController@tag')->name('tag');




});

Route::get('/custom', function(){
	return view('user.custom.list');
});




// middelware


/*Admin Route*/
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middelware' => 'auth:admin'], function(){


	// Route Login Admin
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');

	// Route login post 
	Route::post('login', 'Auth\LoginController@login');

	// Logout Admin 
	// Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

	/*Route Admin Dashboard*/
	Route::get('/dashboard','DashboardController@index')->name('admin.dashboard');

	// Users Admin manage
	Route::resource('user', 'UserController');

	// Role Route
	Route::resource('role', 'RoleController');

	// Permission Route
	Route::resource('permission', 'PermissionController');


	/*Route Blog*/
	Route::group(['namespace' => 'Blog','prefix' => 'blog'], function(){
			
		/*Post Prefix Route*/
		Route::prefix('post')->group(function(){


			// permanent delete
			Route::get('/kill/{id}','PostController@kill')->name('post.kill');
			// showTrash
			Route::get('/show_trashed','PostController@showTrash')->name('post.showTrash');
			// Restored trash
			Route::get('/restore/{id}','PostController@restore')->name('post.restore');
			// doftDelete
			Route::get('/trash{id}', 'PostController@trash')->name('post.trash');

			// Update 
			Route::post('/update/{id}', [
				'uses' => 'PostController@update',
				'as' => 'post.update'
			]);


			// edit 
			Route::get('/edit/{id}','PostController@edit')->name('post.edit');
			// delete thumbnail post 
			Route::delete('/edit/{id}','PostController@deleteThumb')->name('deletethumb');

			Route::post('/create','PostController@store')->name('post.store');
			Route::get('/create', 'PostController@create')->name('post.create');
			Route::get('/', 'PostController@index')->name('post.index');

		
		});

		/*route Category*/
		Route::resource('/category', 'CategoryController');


		/*Route Tag*/
		Route::resource('/tag','TagController');

	});

});

app/Http/Controllers/Admin/Blog/CategoryController.php
<?php

namespace Devmus\Http\Controllers\Admin\Blog;

use Devmus\Http\Controllers\Controller;
use Devmus\Model\Admin\Blog\Category;
use Devmus\Model\Admin\Blog\Post;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');

        $this->middleware('can:posts.category');
        
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.blog.category.index')->with('categories',Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.blog.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|unique:categories,name',
        ]);

        $category = new Category;
        $category->name = $request->name;
        $category->slug = str_slug($request->name);
        $category->save();

        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id); 

        return view('admin.blog.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|unique:categories,name',
            // 'slug' => 'required|unique:categories,slug'
        ]);

        $category = Category::find($id);
        $category->name = $request->name;
        $category->slug = str_slug($request->name);
        $category->save();

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {


        $category = Category::find($id);

        // $category->posts()->delete(); // See below

        $category->delete();

        Post::whereCategoryId($id)->update(['category_id' => null]);
    

        return redirect()->back();

    }
}

app/Http/Controllers/Admin/Blog/PostController.php
<?php

namespace Devmus\Http\Controllers\Admin\Blog;

use Devmus\Http\Controllers\Controller;
use Devmus\Model\Admin\Blog\Category;
use Devmus\Model\Admin\Blog\Post;
use Devmus\Model\Admin\Blog\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Session;
use Storage;
use Validator;

class PostController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('id','desc')->get();

        $category = Category::find('posts');

        $tags = Tag::find('posts');


        return view('admin.blog.post.index', compact('posts','category','tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('posts.create')) {

            $tags = Tag::all();
            $categories = Category::all();

            // jika belum punya akan refirect ke category

            if ($categories->count() ==0 )
            {
                return redirect()->route('category.create');
                
            } else if ($tags->count() == 0) 
            {
                return redirect()->route('tag.create');
            }

            return view('admin.blog.post.create')->with('categories', $categories)
            ->with('tags',$tags);
                
        }

        return redirect()->route('admin.dashboard');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request->all();
        // $input = $request->all();

        $validator = Validator::make($request->all(),[
            'title' => 'required|max:225',
            'slug' => 'required|alpha_dash|min:5|max:225|unique:posts,slug',
            'image' => 'required|image',
            'body' => 'required',
            // 'category_id' => 'required',
            'tags' => 'required'
        ]);

        if ($validator->fails()) {

            return redirect(route('post.create'))->withErrors($validator)->withInput();
        }

        $image = $request->file('image');

        $slug = $request->slug;
        
        // change uniq name
        // $random = rand(1,9999);

        // $image_new_name = time().$slug . $random . '.'. $image->getClientOriginalExtension();

        // $saveImage = $image->storeAs('media', $image_new_name);
        

        $saveImage = $image->store('thumbnail');



        $post = Post::create([
            'title' => $request->title,
            'slug' => $slug,
            'image' => $saveImage,
            'status' => $request->status,
            'admin_id' => $request->admin_id,
            'body' => $request->body,
            'category_id' => $request->category_id,
            
        ]); 

       $post->tags()->sync($request->tags);


        return redirect()->route('post.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::with('tags','category')->where('id',$id)->first();

        $categories = Category::all();

        $tags = Tag::all();

        return view('admin.blog.post.edit')->with('post',$post)->with('categories',$categories)->with('tags',$tags);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        // Validati data 
        $post = Post::find($id);

        if ($request->input('slug') == $post->slug) {
            
            $this->validate($request,[
                'title' => 'required',
                
                'body' => 'required',
                // 'category_id' => 'required',
                'tags' => 'required'
            ]);
        } else {
            
            $this->validate($request,[
                'title' => 'required',
                'slug' => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
                'body' => 'required',
                // 'category_id' => 'required',
                'tags' => 'required'
            ]);
        }

        // post dengan gambar
        $postImage = $post->image;

        // tmpung gmbr baru
        $image = $request->file('image');

        // jika ada file request baru mk hapus yg lama
        if ($image) {

            // delete file
            // dd($postImage);
            
            Storage::delete($postImage);
        }


        // inisialisasi slug
        $slug = $request->slug;
            
            // change uniq name
        // $random = rand(1,9999);

        // $image_new_name = time().$slug . $random . '.'. $image->getClientOriginalExtension();
       

       // jika ada file baru simpan ke database dan storage
        if ($image) {
            
            $saveImage = $image->store('thumbnail');
            
            $post->image = $saveImage;
        
        }


        


        $post->title = $request->title;


        $post->slug = $slug;

        $post->admin_id = $request->admin_id;
        
        $post->body = $request->body;

        $post->status =$request->status;
        
        $post->category_id = $request->category_id;
        
        $post->tags()->sync($request->tags);
        
        $post->save();

        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function trash($id)
    {
        $post = Post::find($id);

        $post->delete();

        return redirect()->back();
    }

    /*show trashed*/

    public function showTrash()
    {
        $posts = Post::onlyTrashed()->get();

        return view('admin.blog.post.trash')->with('posts',$posts);
    }

    /*
    Permanent Delete Post

    */
    public function kill($id)
    {
        $post = Post::withTrashed()->where('id',$id)->first();

        $post->tags()->detach();

        $post->forceDelete();

        // jika punya gambar thumbnal mk hapus
        if ($post->image) {
            
            Storage::delete($post->image);
        }


        return redirect()->back();

    }


    /*Restore from trashed*/
    public function restore($id)
    {

        $post = Post::withTrashed()->where('id',$id)->first();

        $post->restore();

        return redirect()->route('post.index');
    }



    // Delete Thumbnail post edit 
    public function deleteThumb(Request $request, $id)
    {

        $post = Post::find($id);
        // post dengan gambar
        $postImage = $post->image;

        Storage::delete($postImage);

        $post->image = null;
        $post->save();
   
        return redirect()->back();

    }




}

app/Http/Controllers/Admin/Blog/TagController.php
<?php

namespace Devmus\Http\Controllers\Admin\Blog;

use Session;
use Devmus\Http\Controllers\Controller;
use Devmus\Model\Admin\Blog\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');

        $this->middleware('can:posts.tag');

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('admin.blog.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.blog.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|unique:tags,name',
            // 'slug' => 'required'
        ]);

        $tag = new Tag;

        $tag->name = $request->name;
        $tag->slug = str_slug($request->name);
        $tag->save();

        Session::flash('success', 'Tag berhasil di Tambahkan');

        return redirect()->route('tag.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::where('id',$id)->first();

        return view('admin.blog.tag.edit')->withTag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|unique:tags,name',
            // 'slug' => 'required'
        ]);

        $tag = Tag::find($id);

        $tag->name = $request->name;
        $tag->slug = str_slug($request->name);
        $tag->save();

        // Session::flash('success', 'Tag berhasil di Tambahkan');

        return redirect()->route('tag.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);

        // $tag->posts()->detach();

        $tag->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/User/BlogController.php
<?php

namespace Devmus\Http\Controllers\User;

use Devmus\Http\Controllers\Controller;
use Devmus\Model\Admin\Blog\Category;
use Devmus\Model\Admin\Blog\Post;
use Devmus\Model\Admin\Blog\Tag;
// use Devmus\Model\User\Like;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BlogController extends Controller
{

	// Blog list 
	public function list()
	{
		$posts = Post::orderBy('id','desc')->where('status', 1)->paginate(5);


        $zero = 'Post Not Yet';

		return view('front.blog.list',compact('posts' ,'zero'));

	}



    public function post($slug)
    {
    	// fetch from the DB based on slug  status publish
    	$post = Post::where('slug', '=', $slug)->where('status',1)->first();


    	return view('front.blog.post', compact('post'));
    }


    public function category(Category $category)
    {
        $posts = $category->posts();

        $zero = 'Post Not Yet';

        return view('front.blog.list',compact('posts' ,'zero'));
    }
    
    public function tag(Tag $tag)
    {
        $posts = $tag->posts();

        $zero = 'Post Not Yet';

        return view('front.blog.list',compact('posts' ,'zero'));
    }



}

resources/views/admin/blog/tag/create.blade.php
{{-- Tag Create --}}

@extends('admin.main')



@section('content')

<div class="row">
<div class="col-md-12">
{{-- include pesan error --}}
@include('admin.partials._error')
	<form role="form" action="{{ route('tag.store') }}" method="post">
		{{ csrf_field() }}
	    <div class="box box-default">
	        <div class="box-header with-border">
	          <h3 class="box-title">Tag Create</h3>
	        </div>
	        <!-- /.box-header -->
	        <div class="box-body">
	          	<div class="row">
		            <div class="col-md-6 col-md-offset-3">
			              <div class="box-body">
				                <div class="form-group">
					                  <label for="name">Title</label>
					                  <input type="text" class="form-control" id="name" name="name" placeholder="Enter Tag name" autocomplete="off">
				                </div>
				          {{--       <div class="form-group">
				                  <label for="slug">Slug</label>
				                  <input type="text" class="form-control" id="slug" name="slug" placeholder="slug">
				                </div> --}}
				          </div> <!-- box -->
				          <div class="form-group">
				          	<a href="{{ route('tag.index') }}" class="btn btn-warning">Back</a>
				          	<input type="submit" value="submit" class="btn btn-success">
				          </div>
				    </div> <!-- col -->
				</div><!-- row -->
			</div> <!-- box-body -->
		</div> <!-- box-default -->
	</form>	 <!-- form -->

</div>
</div>

@endsection

resources/views/admin/blog/tag/edit.blade.php
{{-- Tag edit --}}

@extends('admin.main')


@section('content')

<div class="col-md-12">
	@include('admin.partials._error')
	
	<form role="form" action="{{ route('tag.update',['id'=>$tag->id]) }}" method="post">
		{{ csrf_field() }}
		{{ method_field('PUT') }}
	    <div class="box box-default">
	        <div class="box-header with-border">
	          <h3 class="box-title">Tag Create</h3>
	        </div>
	        <!-- /.box-header -->
	        <div class="box-body">
	          	<div class="row">
		            <div class="col-md-6 col-md-offset-3">
			              <div class="box-body">
				                <div class="form-group">
					                  <label for="Name">Name</label>
					                  <input type="text" class="form-control" name="name" id="Name" value="{{ $tag->name }}">
				                </div>
				               {{--  <div class="form-group">
				                  <label for="slug">Slug</label>
				                  <input type="text" class="form-control" name="slug" id="slug" value="{{ $tag->slug }}">
				                </div> --}}
				          </div> <!-- box -->
				          <div class="box-footer">
				          	<a href="{{ route('tag.index') }}" class="btn btn-warning">Back</a>
				          	<input type="submit" value="submit" class="btn btn-success">
				          </div>
				    </div> <!-- col -->
				</div><!-- row -->
			</div> <!-- box-body -->
		</div> <!-- box-default -->
	</form>	 <!-- form -->

</div>

@endsection

resources/views/admin/blog/tag/index.blade.php
{{-- index Tags --}}
@extends('admin.main')


@section('css')

  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">

@endsection

@section('content')
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="box-header">
              <a href="{{ route('tag.create') }}" class="btn btn-warning">Create</a>
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>No.</th>
                  <th>Name</th>
                  <th>Slug</th>
                  <th>Delete</th>
                </tr>
                </thead>
                <tbody>

                  @foreach ($tags as $tag)
                <tr>
                    
                  <td>{{ $loop->index +1 }} </td>
                  <td>{{ $tag->name }} </td>
                  <td>{{ $tag->slug }} </td>
                  <td>
                    <form method="post" id="delete-form-{{ $tag->id }}" action="{{ route('tag.destroy',['id'=>$tag->id]) }}">
                      {{ csrf_field() }}
                      {{ method_field("DELETE") }}
                    </form>
                    <a href="{{ route('tag.edit',$tag->id) }}"><span class="label label-warning">Edit</span></a>
                   |
                    <a href="" onclick="if (confirm('Are you Sure???')) {
                      event.preventDefault();
                      document.getElementById('delete-form-{{ $tag->id }}').submit();
                    } else {
                      event.preventDefault();
                    } ">Delete</a> 
                 </td>
                </tr>
                  @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Total</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
@endsection

@section('javascript')
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script>
  $(function () {
    $('#example1').DataTable()
  })
</script>
@endsection