routes/web.php
<?php


// Route::get('/test', function() {
// 	return Devmus\Model\User\Profile::find(1)->user;
// });


Auth::routes();



/*Front End*/
Route::namespace('User')->group(function(){

	Route::get('/', 'HomeController@index')->name('home');


	// Profile
	Route::get('/dashboard', 'ProfileController@index')->name('user.dashboard');
	Route::post('/dashboard', 'ProfileController@update');
	Route::delete('/dashboard', 'ProfileController@destroy');


	// Blog

	Route::get('/', 'BlogController@list')->name('blog');
	
	Route::get('/{slug}', 'BlogController@post')->name('post');

	Route::get('/category/{category}', 'BlogController@category')->name('category');

	Route::get('/tag/{tag}', 'BlogController@tag')->name('tag');




});

Route::get('/custom', function(){
	return view('user.custom.list');
});




// middelware


/*Admin Route*/
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middelware' => 'auth:admin'], function(){


	// Route Login Admin
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');

	// Route login post 
	Route::post('login', 'Auth\LoginController@login');

	// Logout Admin 
	// Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

	/*Route Admin Dashboard*/
	Route::get('/dashboard','DashboardController@index')->name('admin.dashboard');

	// Users Admin manage
	Route::resource('user', 'UserController');

	// Role Route
	Route::resource('role', 'RoleController');

	// Permission Route
	Route::resource('permission', 'PermissionController');


	/*Route Blog*/
	Route::group(['namespace' => 'Blog','prefix' => 'blog'], function(){
			
		/*Post Prefix Route*/
		Route::prefix('post')->group(function(){


			// permanent delete
			Route::get('/kill/{id}','PostController@kill')->name('post.kill');
			// showTrash
			Route::get('/show_trashed','PostController@showTrash')->name('post.showTrash');
			// Restored trash
			Route::get('/restore/{id}','PostController@restore')->name('post.restore');
			// doftDelete
			Route::get('/trash{id}', 'PostController@trash')->name('post.trash');

			// Update 
			Route::post('/update/{id}', [
				'uses' => 'PostController@update',
				'as' => 'post.update'
			]);


			// edit 
			Route::get('/edit/{id}','PostController@edit')->name('post.edit');
			// delete thumbnail post 
			Route::delete('/edit/{id}','PostController@deleteThumb')->name('deletethumb');

			Route::post('/create','PostController@store')->name('post.store');
			Route::get('/create', 'PostController@create')->name('post.create');
			Route::get('/', 'PostController@index')->name('post.index');

		
		});

		/*route Category*/
		Route::resource('/category', 'CategoryController');


		/*Route Tag*/
		Route::resource('/tag','TagController');

	});

});

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace Devmus\Http\Controllers\Admin;

use Devmus\Model\Admin\Permission;
use Illuminate\Http\Request;
use Devmus\Http\Controllers\Controller;


class PermissionController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');

        $this->middleware('can:users.permission');
    }




    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $permissions = Permission::all();


        return view('admin.permission.index', compact('permissions'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.permission.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' =>'required|max:50|unique:permissions',
            'for' => 'required'
        ]);

        $permission = new Permission;

        $permission->name = $request->name;

        $permission->for = $request->for;

        $permission->save();


        return redirect()->route('permission.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \Devmus\Model\Admin\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function show(Permission $permission)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Devmus\Model\Admin\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        $permission = Permission::find($permission->id);

        return view('admin.permission.edit',compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Devmus\Model\Admin\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $this->validate($request, [
            'name' => 'required|max:50',
            'for' => 'required'
        ]);

        $permission = Permission::find($permission->id);

        $permission->name = $request->name;

        $permission->for = $request->for;

        $permission->save();

        return redirect()->route('permission.index')->with('message', 'Permission Update Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Devmus\Model\Admin\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        Permission::where('id', $permission->id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/permission/create.blade.php
{{-- Permission Create --}}

@extends('admin.main')



@section('content')

<div class="row">
<div class="col-md-12">
{{-- include pesan error --}}
@include('admin.partials._error')
	<form role="form" action="{{ route('permission.store') }}" method="post">
		{{ csrf_field() }}
	    <div class="box box-default">
	        <div class="box-header with-border">
	          <h3 class="box-title">Permission Create</h3>
	        </div>
	        <!-- /.box-header -->
	        <div class="box-body">
	          	<div class="row">
		            <div class="col-md-6 col-md-offset-3">
			              <div class="box-body">
				                <div class="form-group">
					                  <label for="name">Permission</label>
					                  <input type="text" class="form-control" id="name" name="name" placeholder="Enter Permission name" autocomplete="off">
				                </div>
				          
								<div class="fotm-group">
									<label for="for">Permisssion for</label>
									<select name="for" id="for" class="form-control">
										<option  selected disabled>Select Permission for</option>
										<option value="user"  >User</option>
										<option value="post" >Post</option>
										<option value="other" >Other</option>
									</select>
								</div>

				          </div> <!-- box -->
				          <div class="form-group">
				          	<a href="{{ route('permission.index') }}" class="btn btn-warning">Back</a>
				          	<input type="submit" value="submit" class="btn btn-success">
				          </div>
				    </div> <!-- col -->
				</div><!-- row -->
			</div> <!-- box-body -->
		</div> <!-- box-default -->
	</form>	 <!-- form -->

</div>
</div>

@endsection

resources/views/admin/permission/edit.blade.php
{{-- permission Edit --}}

@extends('admin.main')



@section('content')

<div class="row">
<div class="col-md-12">
{{-- include pesan error --}}
@include('admin.partials._error')
	<form role="form" action="{{ route('permission.update',['id' => $permission->id]) }}" method="post">
		{{ csrf_field() }}
		{{ method_field('PATCH') }}
	    <div class="box box-default">
	        <div class="box-header with-border">
	          <h3 class="box-title">Edit permission :  <b>{{ $permission->name }} </b></h3>
	        </div>
	        <!-- /.box-header -->
	        <div class="box-body">
	          	<div class="row">
		            <div class="col-md-6 col-md-offset-3">
			              <div class="box-body">
				                <div class="form-group">
					                  <label for="name">Permission</label>
					                  <input type="text" class="form-control" id="name" name="name" value="{{ $permission->name }} " autocomplete="off">
				                </div>

				                <div class="fotm-group">
									<label for="for">Permisssion for</label>
									<select name="for" id="for" class="form-control">
										<option  selected disabled>Select Permission for</option>
										<option value="user"  >User</option>
										<option value="post" >Post</option>
										<option value="other" >Other</option>
									</select>
								</div>

				          
				          </div> <!-- box -->
				          <div class="form-group">
				          	<a href="{{ route('permission.index') }}" class="btn btn-warning">Back</a>
				          	<input type="submit" value="submit" class="btn btn-success">
				          </div>
				    </div> <!-- col -->
				</div><!-- row -->
			</div> <!-- box-body -->
		</div> <!-- box-default -->
	</form>	 <!-- form -->

</div>
</div>

@endsection

resources/views/admin/permission/index.blade.php
{{-- index permission --}}
@extends('admin.main')


@section('css')

  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">

@endsection

@section('content')
      <div class="row">
        <div class="col-xs-12">

@include('admin.partials._error')
          <div class="box">
            <div class="box-header">
              <a href="{{ route('permission.create') }}" class="btn btn-warning">Create</a>
              <h3 class="box-title">Permission Create</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>No.</th>
                  <th>Name</th>
                  <th>For</th>
                  <th>Opsi</th>
                </tr>
                </thead>
                <tbody>

                  @foreach ($permissions as $permission)
                <tr>
                    
                  <td>{{ $loop->index +1 }} </td>
                  <td>{{ $permission->name }} </td>
                  <td>{{ $permission->for }} </td>

                  <td>
                    <form method="post" id="delete-form-{{ $permission->id }}" action="{{ route('permission.destroy',['id'=>$permission->id]) }}">
                      {{ csrf_field() }}
                      {{ method_field("DELETE") }}
                    </form>
                    <a href="{{ route('permission.edit',$permission->id) }}"><span class="label label-warning">Edit</span></a>
                   |
                    <a href="" onclick="if (confirm('Are you Sure???')) {
                      event.preventDefault();
                      document.getElementById('delete-form-{{ $permission->id }}').submit();
                    } else {
                      event.preventDefault();
                    } ">Delete</a> 
                 </td>
                </tr>
                  @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Total</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
@endsection

@section('javascript')
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script>
  $(function () {
    $('#example1').DataTable()
  })
</script>
@endsection